---

- name: sohre hosts
  hosts: dns
  gather_facts: true
  roles:
    - dns

- name: k3s hosts
  hosts: k3s
  gather_facts: true
  roles:
    - k3s

- name: everyone
  hosts: all
  gather_facts: true
  roles:
    - update
    - common
  
- name: sohre hosts
  hosts: sohre
  gather_facts: true
  vars:
    soh_router_version: "1.0.11"
  roles:
    - sohre
