---

- name: sohre hosts
  hosts: dns
  gather_facts: true
  roles:
    - dns

- name: Playbook
  hosts: all
  gather_facts: true
  roles:
    - update
    - common
  
- name: sohre hosts
  hosts: sohre
  gather_facts: true
  vars:
    soh_router_version: "1.0.11"
  roles:
    - sohre
