---
- name: Ensure dir exists for backup_dirs
  file:
    state: directory
    path: "/mnt/backup/{{ inventory_hostname }}{{ item }}"
  with_items:
    - "{{ backup_dirs }}"
  delegate_to: localhost

- name: Ensure dir exists for backup_files
  file:
    state: directory
    path: "/mnt/backup/{{ inventory_hostname }}{{ item | dirname }}"
  with_items:
    - "{{ backup_files }}"
  delegate_to: localhost

- name: Grab files from phy01
  shell: rsync -avz --delete {{ inventory_hostname }}:{{ item }} /mnt/backup/{{ inventory_hostname }}/{{ item }}
  with_items:
    - "{{ backup_dirs }}"
    - "{{ backup_files }}"
  delegate_to: localhost
